### ISSUE TITLE
Iframe+ doesnt work in Chrome

### ISSUE THREAD

**Issue by Britain4** [cm0s/iframe-plus-portlet#3]
Hello, Nicolas.
Thanks for the great source. But i have little problems with your Iframe+. I am new in liferay and in web programming. Iframe+ works fine for IE8 and Firefox 7.0.1 but doesnt work for IE7 and Chrome 17.0.963.79 m. I see that u are using document.body.clientHeight in iframe-plus.js in resizeIframe() method. I alert(document.body.clientHeight) and it gives 100 in IE7 and chrome and gives 217 (the height of the page) in Mozilla and ie8. Actually, now, i see in Firefox and IE8 it doesnt work in inner pages (after i log in). Do u have any suggestions why it doenst work, i have included the scripts (and i checked, they are included) and i set the css style

**Comment by cm0s** [comment]
Hi,

Thank you for your feed back.

I will check this issue as soon as possible. I will keep you informed.

**Comment by cm0s** [comment]
Hi,

I rechecked and I didn't get any issue with IE7+ neither with Google Chrome 17+. Perhaps it comes from the content of your Provider page (the child page). If it's possible you can send me your page or an example which makes the bug appears and I will check it.

See you

**Comment by Britain4** [comment]
HI,
I fixed it
Thank you
