### ISSUE TITLE
frame displays incorrectly

### ISSUE THREAD

**Issue by dweebman** [cm0s/iframe-plus-portlet#5]
I want to thank you for sharing this portlet. I was astonished at how fast it loaded compared to LR's iframe portlet. However, It doesn't display correctly for me. I have a php app on same server as portal. When I configure iframe+ it displays like this:

![iframe](https://f.cloud.github.com/assets/3767489/217802/4f5a09f6-84f7-11e2-857e-0675552df63c.png)

I am sure its user error : -) thanks again

**Comment by cm0s** [comment]
Hello,

Sorry for the delay.

Could you please send a better screenshot and a better description of the display problem? 

Your screenshot is really small and not really self-explanatory.

Thank you
