### ISSUE TITLE
Docs not quite clear

### ISSUE THREAD

**Issue by kastork** [cm0s/iframe-plus-portlet#6]
The documentation contains these two paragraphs

Installation for the configuration n°2 is similar to the configuration n°1. However, you have to create the Intermediary page and make it accessible. You can create the Intermediary page by using the css and the javascript files located in /docroot/js/iframeplus/iframeplus-intermediate.js and /docroot/js/iframeplus/iframeplus-intermediate.css, you can also use the /docroot/js/iframeplus/iframeplus-intermediary.html file which already contains the correct javascript lines of codes and css styles.

Once the Intermediary page created you have to indicates through the configuration page of the portlet (see "IFrame+ portlet configuration options" screenshot at the begining of the README) the URL of the Intermediary page you just created. The url must have an "url" parameter which contain the URL of the home page. For exemple, if your Intermediary page URL is : http://your.webapp.com/intermediary and your main page is http://your.webapp.com, the URL to put into the "Web site URL" field of the portlet configuration page is : http://your.webapp.com/intermediary?url=http://your.webapp.com

This leaves me with a question.

How do I construct the compound URL if I just want to use your provided intermediary page?

Say I have Liferay running here

```
http://mydomain:8080
```

with a iFrame+ instance on a page called foopage

And say I have some other web app running here

```
http://myotherdomain:9000/app
```

I understand the URL needs to look like

```
<intermediaryURL>?url=http://myotherdomain:9000/app
```

Okay, so I want to use your supplied intermediary page

I've tried

```
js/iframeplus/iframeplus-intermediary.html?http://myotherdomain:9000/app
```

and

```
/js/iframeplus/iframeplus-intermediary.html?http://myotherdomain:9000/app
```

None of these work for me.

So if you could please document how to construct the URL when using your supplied intermediary, it would be great.

Thanks again.

**Comment by cm0s** [comment]
Hi kastork,

Sorry for the long delay. I don't know if an answer is still relevant now...

I think you misunderstood the documentation (perhaps it's not sufficiently clear?).

As described on the schema the intermediate page has to be located inside your

```
http://myotherdomain:9000/app. 
```

Here is the url you have to use :

```
 http://myotherdomain:9000/app/iframeplus-intermediary.html?http://myotherdomain:9000/app
```

The iframeplus-intermediary.html file must be hosted on myotherdomain:9000

**Comment by kastork** [comment]
Thanks Niclolas, that's helpful.
