### ISSUE TITLE
Does not resize

### ISSUE THREAD

**Issue by archim** [cm0s/iframe-plus-portlet#7]
I am using LR 6.1 EE and WAS8 server.

I deployed portlet and added to the page. Configured portlet to manually resize.

I see loading message for long time but loading never completes.

Am I missing something here? I do not get any errors in chrome web 
![Uploading iframe-plus.png . . .]()
error console.

**Comment by cm0s** [comment]
Did you tried to set the loading mask option to automatic?

If you want to stop manually the Loading mask, you have to stop it manually from the iframe content page with the hideLoadingMask() javascript function.

Please have a look at the [documentation](https://github.com/cm0s/iframe-plus-portlet#loading-mask-option).

It's really important to carefully read the documentation to be able to correctly configure your environment and thus make the resize and loading mask functionalities works.
